---

- name: create docker group
  group:
    gid: 1991
    name: docker
    state: present

- name: add docker group
  user:
    name: fedora
    groups: docker
    append: true
 
- name: enable docker services
  service:
    name: docker
    enabled: true
    state: started
