---

- name: Creating config
  file:
    path: "/etc/logstash/config"
    state: directory
    mode: 0777

- name: Copy config
  template:
    src: "logstash.yml.j2"
    dest: "/etc/logstash/config/logstash.yml"
    mode: 0766

- name: Copy pipelines config
  template: 
    src: "pipeline.yml.j2"
    dest: "/etc/logstash/config/piplines.yml"
    mode: 0766

- name: Copy Pipelines directory
  file:
    path: "/etc/logstash/config/pipeline"
    state: directory
    mode: 0777

- name: Copy pipeline_1 configuration
  template:
    src: "pipeline.conf.j2"
    dest: "/etc/logstash/config/pipeline/pipeline.conf"
    mode: 0766